version: '3.8'

services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: issue_tracker
      POSTGRES_PASSWORD: issue_tracker
      POSTGRES_DB: issue_tracker
    ports:
      - "5432:5432"